version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /application
        volumes:
            - '.:/application'
            - './db/:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=Timbratrice
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
        ports:
            - '40002:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '40000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'

    # my_sailapplication:
    #     build: 
    #         context: ./my_sailapplication
    #         dockerfile: dockerfile
    #     # networks:
    #     #     - my_sailapplication
    #     environment:
    #         - DB_DATABASE=mysql
    #         - DB_HOST=mysql
    #         - DB_PORT=3306
    #         - DB_DATABASE=Timbratrice
    #         - DB_USERNAME=root
    #         - DB_PASSWORD=root
    #     depends_on:
    #         - mysql
    #     ports:
    #         - 8000:8000
    #     volumes:
    #         - '.:/application'
    #         - '.:/my_sailapplication'

    app:
        image: node:14-alpine
        # build: 
            # context: ./timbratrice2
            # dockerfile: dockerfile
        # networks:
        #     - application
        volumes:
        - ./timbratrice2:/application
        working_dir: /application
        tty: true
        # depends_on:
        #     - my_sailapplication
        ports:
        - 3000:3000
        command: npm start
